### ISSUE TITLE
Invalid metadata for phf_macros when trying to test with coverage.

### ISSUE THREAD

**Issue by Drako** [rust-phf/rust-phf#267] opened 2022-08-12 12:47 UTC
Operating System: Windows 11 Professional 64 Bit
Toolchain: stable-x86_64-pc-windows-msvc
Rust Version: rustc 1.62.0 (a8314ef7d 2022-06-27)
phf Version: 0.11.1 with feature "macros"

Normal compilation and testing works.
When running the tests with coverage though, I get the following errors:

```
C:/Users/drako/.cargo/bin/cargo.exe +stable test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --lib lexer::tests --manifest-path C:\Users\drako\Desktop\Projects\asm-rs\assembly\Cargo.toml
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling siphasher v0.3.10
   Compiling rand_core v0.6.3
   Compiling syn v1.0.99
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.1
   Compiling phf_generator v0.11.1
   Compiling phf_macros v0.11.1
   Compiling phf v0.11.1
error[E0786]: found invalid metadata files for crate `phf_macros`
   --> C:\Users\drako\.cargo\registry\src\github.com-1ecc6299db9ec823\phf-0.11.1\src/lib.rs:105:9
    |
105 | pub use phf_macros::phf_map;
    |         ^^^^^^^^^^
    |
    = note: failed to decompress metadata: \\?\C:\Users\drako\Desktop\Projects\asm-rs\target\debug\deps\phf_macros-4175faaf2b68124a.dll

error[E0786]: found invalid metadata files for crate `phf_macros`
   --> C:\Users\drako\.cargo\registry\src\github.com-1ecc6299db9ec823\phf-0.11.1\src/lib.rs:111:9
    |
111 | pub use phf_macros::phf_ordered_map;
    |         ^^^^^^^^^^
    |
    = note: failed to decompress metadata: \\?\C:\Users\drako\Desktop\Projects\asm-rs\target\debug\deps\phf_macros-4175faaf2b68124a.dll

error[E0786]: found invalid metadata files for crate `phf_macros`
   --> C:\Users\drako\.cargo\registry\src\github.com-1ecc6299db9ec823\phf-0.11.1\src/lib.rs:132:9
    |
132 | pub use phf_macros::phf_set;
    |         ^^^^^^^^^^
    |
    = note: failed to decompress metadata: \\?\C:\Users\drako\Desktop\Projects\asm-rs\target\debug\deps\phf_macros-4175faaf2b68124a.dll

error[E0786]: found invalid metadata files for crate `phf_macros`
   --> C:\Users\drako\.cargo\registry\src\github.com-1ecc6299db9ec823\phf-0.11.1\src/lib.rs:138:9
    |
138 | pub use phf_macros::phf_ordered_set;
    |         ^^^^^^^^^^
    |
    = note: failed to decompress metadata: \\?\C:\Users\drako\Desktop\Projects\asm-rs\target\debug\deps\phf_macros-4175faaf2b68124a.dll

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0786`.
error: could not compile `phf` due to 5 previous errors
Process finished with exit code 101
```

I also tried `cargo clean` as that was suggested for similar issues, but that didn't change anything.

I'm not sure, if that is a Rust issue or a phf issue.
I also tried to use `rustc 1.65.0-nightly (d394408fb 2022-08-07)`, but that had the same results.

**Comment by JohnTitor** [comment] 2022-08-12 14:17
Could you provide a reproducible example? I cannot reproduce it on my end. Does v0.11.0 or prior work for you? Also, please try to delete your target dir manually.

**Comment by Drako** [comment] 2022-08-12 21:14
So one thing after the other:

1. I tried deleting target/ manually. That did not change anything.
2. I tried v0.11.0 as you suggested (also with deleting target/) but that also didn't change anything.
3. I tried it on MacOS and there everything works fine.

This is the project I am currently working on, which triggers the error:
https://git.drako.guru/drako/asm-rs

And again, it specifically happens, when trying to test with coverage.
Regular building/testing/running works without issues.

I'm using CLion with the Rust Plugin, which has a nice "Run <X> with coverage" button.
But that basically just executes the cargo command you can see at the beginning of the error log above.

**Comment by Drako** [comment] 2022-08-12 21:27
I manually ran
`cargo +stable test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --lib lexer::tests --manifest-path ass
embly/Cargo.toml`
in WSL, as CLion doesn't support WSL toolchains yet.

So right now my guess is, that his is a DLL specific issue.

**Comment by Drako** [comment] 2022-08-12 21:59
Last but not least I tested it now on an actually installed Linux (Manjaro) and there it also works as expected.

So yeah... I suppose DLLs, procedural macros and coverage data may an issue with each other :/

**Comment by JohnTitor** [comment] 2022-08-15 12:15
Thanks for investigating! Hmm, so based on your comments, the issue seems to be outside of the phf crate. If there's an actionable item, e.g. a workaround, I'm happy to accept that, but I haven't come up with a solution here :(

**Comment by JonathanVusich** [comment] 2022-12-07 14:56
This appears to be a `rustc` issue: https://github.com/rust-lang/rust/issues/90056. Using the flag `--target x86_64-pc-windows-msvc` fixed the compiler issue for me.

**Comment by JohnTitor** [comment] 2022-12-08 07:37
Thank you for the information! Then I will close this as there's no actionable item on rust-phf.

**Closed by JohnTitor** 2022-12-08 07:37 UTC
